/*
===============================================================================

-- Magnitude Analysis --

Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find the total customers by countries
SELECT 
	country, 
	COUNT(DISTINCT customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender
SELECT 
	gender, 
	COUNT(DISTINCT customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
	category, 
	COUNT( product_key) AS total_products 
FROM gold.dim_products
GROUP BY category 
ORDER BY total_products DESC;

-- Find the average costs in each category
SELECT 
	category, 
	AVG(cost) AS average_cost 
FROM gold.dim_products
GROUP BY category 
ORDER BY average_cost DESC;

-- Find the total revenue generated for each category
SELECT 
	p.category,
	SUM(s.sales_amount) AS total_revenue 
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p 
	ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customers
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS total_revenue 
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c 
	ON s.customer_key = c.customer_key
GROUP BY c.customer_key, 
		 c.first_name, 
		 c.last_name
ORDER BY total_revenue DESC;

-- Find the distribution of items sold across countries

SELECT
	c.country,
	SUM(f.quantity) AS total_sold_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
	ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_quantity DESC;
